---
title: "I_AFMOS_1a_ambient_v3_0"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## SoupX analysis


```{r input}
library(SoupX)
library(Matrix)
# https://rawcdn.githack.com/constantAmateur/SoupX/650f7fa30b6c985486953b9ef8858c17fe7df68a/inst/doc/pbmcTutorial.html
dir_in <- '/Users/davfischer/Documents/science/collideseq/data/P21037/cellranger/'
dir_out <- '/Users/davfischer/Documents/science/collideseq/data/soupx/'
```

## Sample MUC29498
Note that directory structure must be [analysis/, raw_feature_bc_matrix/, filtered_feature_bc_matrix/] and all files in raw_feature_bc_matrix, filtered_feature_bc_matrix must be .gz.
```{r fn1, echo=TRUE}
sc1 = load10X(dataDir=paste0(dir_in, 'MUC29498/'), verbose=TRUE)
sc1 = autoEstCont(sc1)
out1 = adjustCounts(sc1)
writeMM(out1, paste0(dir_out, 'MUC29498/', 'matrix.mtx'))
```

## Sample MUC29499

```{r fn2, echo=TRUE}
sc2 = load10X(dataDir=paste0(dir_in, 'MUC29499/'), verbose=TRUE)
sc2 = autoEstCont(sc2)
out2 = adjustCounts(sc2)
writeMM(out2, paste0(dir_out, 'MUC29499/', 'matrix.mtx'))
```

